ver = "0.2.8"

[[tests]]
name = "Gold"
paths = [ "polybench/*.fuse" ]
cmd = """
./bin/dahlia-run {} {}.data
"""
expect_dir = "simulation/"


[[tests]]
name = "Correctness"
paths = [ "polybench/*.fuse" ]
cmd = """
fud exec -s verilog.data {}.data \
         {} --to dat \
         -q
"""
expect_dir = "simulation/"

[[tests]]
name = "Unrolled"
paths = [ "unrolled/*.fuse" ]
cmd = """
fud exec -s verilog.data {}.data \
         {} --to dat \
         -q
"""
expect_dir = "simulation/"

